authorName: Vincent
experimentName: bert
trialConcurrency: 1
maxExecDuration: 7h
maxTrialNum: 50
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
logDir: /uac/rshr/cyliu/bigDataStorage/moo/chen.yu/log
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python worker.py
  codeDir: .
  gpuNum: 0
