authorName: Vincent
experimentName: Resnet50
trialConcurrency: 1
maxExecDuration: 10h
maxTrialNum: 150
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
advisor:
  builtinAdvisorName: BOHB
  classArgs:
    optimize_mode: maximize
    min_budget: 1
    max_budget: 12
    eta: 3
    min_points_in_model: 7
    top_n_percent: 15
    num_samples: 64
    random_fraction: 0.0 #0.33
    bandwidth_factor: 3.0
    min_bandwidth: 0.001
trial:
  command: python resnet.py
  codeDir: .
  gpuNum: 1
